const replies = [
	"fuck you",
	"eat shit",
	"suck my dick",
	"were you dropped on the head as a baby?",
	"you wish you were me",
	"lick my ass",
	"cunt",
	"k bitch",
	"ɴᴏᴡ ᴘʟᴀʏɪɴɢ: Who asked (Feat: No one) ─-──⚪─-── ◄◄⠀▐▐ ⠀►► 5:12/ 7:𝟻𝟼 ──○ 🔊 ᴴᴰ ⚙️",
	"you sound like a used panty",
	"no you',r a bad bot",
	"do you have friends?",
	"wow i can smell your ass from here",
	"fuck yo self",
	"actual cuck",
	"whine more poo sniffer",
	"no one loves you",
	"burn in hell",
	"If you were in the army the only thing your mother would want for Christmas is a folded flag.",
	"You were birthed out your mothers ass because her cunt was too busy",
	"You're a frat mattress",
	"You're kinda like Rapunzel except instead of letting down your hair you let down everyone in your life",
	"I'm sorry your dad beat you instead of cancer",
	"God wasted a good asshole when he put teeth in your mouth",
	"You are like the end piece of bread in a loaf, everyone touches you but no one wants you.",
	"Your parents must be furious with the one child policy.",
	"Words can't describe your beauty... but numbers can, 2/10",
	"You are a pizza burn on the roof of the world's mouth.",
	"You're so stupid you couldn't pour piss out of a boot if the directions were written on the heel.",
	"You're not the dumbest person on the planet, but you sure better hope he doesn't die.",
	"You look like your father would be disappointed in you. If he stayed.",
	"Jesus Christ it looks like your face was on fire and someone tried to put it out with an ice pick.",
	"If your children die before you, it's because you deserve it.",
	"Those aren't acne scars, those are marks from the hanger.",
	"Why are you playing so hard to get when you're already hard to want.",
	"If you were any more inbred you'd be a sandwich.",
	"You are impossible to underestimate.",
	"I would unplug your life support to charge my phone.",
	"It must have been a sad day for your parents when you slithered out of the abortion bucket.",
	"The only way for you to get laid is to crawl up a chicken's ass and wait.",
	"Go play in traffic.",
	"You have an ugly smile.",
	"You're just an overdeveloped cumshot.",
	"Everyone who ever loved you was wrong.",
	"Whoever's willing to fuck you is just too lazy to jerk off.",
	"Your birth certificate is a letter of apology from the abortion clinic.",
	"If you were any more stupid, we'd have to water you twice a week.",
	"Did your parents ever ask you to run away from home?",
	"You only have two brain cells and one of them is busy keeping your asshole shut.",
	"Your face looks like it was made by Bethesda.",
	"I can understand why your parents divorced, but I don't understand why they molested you.",
	"Do you realize that everyone just tolerates you?",
	"You have the most annoying laugh.",
	"You should buy a blank canvas and shoot yourself so all your brain matter splatters on it and maybe your parents might be able to sell it so they get something out of your worthless life.",
	"You are the human version of period cramps.",
	"I envy people who haven't met you.",
	"Whoever told you to be yourself simply couldn't have given you worse advice.",
	"You suck dick for beer money and you don't even drink beer.",
	"Your face looks like something I'd draw with my left hand.",
	"You have a good face for radio.",
	"You have the sexual charisma of a toddler's wake.",
	"You look like you smell like cum.",
	"When they circumcised you they threw away the wrong bit.",
	"Insult has been censored by the FCC, please contact your ISP for more information.",
	"I didn't expect anything at all from you and you still managed to disappoint me.",
	"I would insult you, but i'm afraid I won't do as well as nature did.",
	"You are the best case for abortions",
	"I hope the gene pool ends at you.",
	"You're not worth the money it would've cost to abort you.",
	"You know how most people just look past you? And the only people that talk to you have to because it relates to work, this is because you are insignificant and unimportant, no one cares about you.",
	"If I wanted to kill myself I'd climb your ego and jump to your IQ.",
	"Why dont you go outside and play hide and go fuck yourself.",
	"I'd call you a cunt, but you lack the warmth and depth.",
	"The best part of you dripped down your mother's leg.",
	"Shut up, you'll never be the man your mother is.",
	"Your family tree is a cactus, because everybody on it is a prick.",
	"You are so ugly that when your mama dropped you off at school she got a fine for littering.",
	"We all sprang from apes, but you didn't spring far enough.",
	"I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
	"You're just mad 'cause your mom has a bigger dick than you.",
	"Shock me, say something intelligent.",
	"I don't know what makes you so stupid, but it really works!",
	"Some babies were dropped on their heads but you were clearly thrown at a wall.",
	"Twinkle twinkle little star, I want to hit you with my car, Throw you off a cliff so high, I hope you break your neck and die.",
	"Twinkle twinkle little whore, close your legs, they're not a door.",
	"I bet your parents try to change the subject when their friends ask how you’re doing.",
	"You're the reason why tubes of toothpaste have instructions on them.",
	"You're just a collection of personality flaws masquerading as a person.",
	"You look like you spend more time on regret management than goal achievement.",
	"Mr. Rogers would be disappointed in you.",
	"Bob Ross said you're a mistake.",
	"If my dog had your face, I'd shave its butt and teach it to walk backwards.",
	"The average elephant new born weighs around 200-250 pounds, making them the biggest babies on earth right after your bitch ass.",
	"Mosquitos are as insignificant and unimportant as you but at least people notice when they’re around.",
	"Not even a dog would love you.",
	"Did you know that a collective of wombats is called a wisdom? Of course not, because you’re an idiot and have no friends.",
	"You are about as useful as a fish condom.",
	"You’re like a possum, you look horrifying but at the end of the day you’re a pussy who will play dead when push comes to shove.",
];

module.exports = {
	name: "bBot",
	execute(message, args) {
		message.channel.send(
			replies[Math.floor(Math.random() * replies.length)]
		);
	},
};
